---
title: "February DW Tournament"
author: "by NN Sheep"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bg: "#FFFFFF"
      fg: "#000000" 
      primary: "#0D0A47"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
    vertical_layout: fill
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE)
library(tidyverse)
library(knitr)
library(flexdashboard)
library(RColorBrewer)

# load in data
raw <- readxl::read_excel('hs_feb.xlsx') 
```

```{r}
#### INITIALISATIONS ####

# plot template
theme_blank <- function(){
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank())}

# dw scoring system
dw_scores <- c(25,22,19,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1)

# function for daily individual results
indiv_df <- function(x,d){
  filter(x,Day==d & !is.na(Time)) %>%
  select(Colour,Rank,Team,Player,Time,
         `Reverse Points`=rev_pts,
         `DW Points`=dw_pts) %>%
  arrange(Rank) %>%
  mutate(Player=fct_reorder(Player,-Rank))
}

# function for final individual results
final_df <- function(x){
  select(x,-c(Day,Car,Track)) %>%
  group_by(Player) %>%
  summarise(Colour=Colour,
            Team=Team,
            Time = round(sum(Time)/n_distinct(x$Day),2),
            dw_pts=sum(dw_pts),
            rev_pts=sum(rev_pts)) %>%
  arrange(Time) %>%
  mutate(Rank = 1:nrow(.),.before = Player,
         Player=fct_reorder(Player,-Rank))
}
```

``` {r}
#### DATA PREP ####
results <- raw %>%
  # remove missing players to avoid error
  filter(!is.na(Player)) %>%
  # if using HS teams, add team colours
  mutate(Colour=recode(Team, 
                       'NN' ='#e53af5',
                       'TD' ='#43F1DE',
                       'EZ' ='#dbb1ff',
                       'YY' ='#7d8072',
                       'EBL'='#ccff00',
                       'RED'='#ea2d45',
                       '-'  ='#FFFFFF')) %>% 
  # gather columns of same type of info and add column for day
  pivot_longer(-c(1:3), values_transform = as.character) %>%
  # collate cols into one day col and one time col
  separate(name,c('Data','Day'),'_') %>% 
  pivot_wider(names_from = Data, values_from = value) %>%
  mutate(Time=round(as.numeric(Time),2), Day=as.numeric(Day)) %>%
  # sort by lowest time for each day 
  arrange(Day,Time) %>%
  # add column for rank based on lowest time
  mutate(Rank=rep(1:n_distinct(Player),n_distinct(Day)),.before=Player) %>%
  # add points based on new rank column
  mutate(rev_pts=rev(Rank),
         dw_pts=rep(dw_scores[1:n_distinct(Player)],n_distinct(Day))) %>%
  # change NAs to 0 in DW points
  mutate(dw_pts=case_when(
    Rank>length(dw_scores)~0,
    .default=dw_pts))
```

# Day 1
```{r}
day=1
tmp<-indiv_df(results,day)
```
##### **Car: `r raw$Car_1[day]`** <br> **Track: `r raw$Track_1[day]`**

Column 
--------------
### Time 
```{r}
# plot team performance
ggplot(tmp, aes(Time,Player,fill=Player)) +
  geom_col(position='dodge', show.legend=FALSE, colour='black') +
  scale_fill_manual(values=rev(tmp$Colour)) +
  coord_cartesian(xlim=c(min(tmp$Time)*.999,max(tmp$Time)**1.002)) +
  theme_blank() + 
  annotate('text', x=rev(tmp$Time)+.07, #for spacing
           y=1:length(tmp$Time), size=2.5,
           label=paste0(format(rev(tmp$Time),nsmall=2),'s'))
```

Column {data-width=300}
--------------
### Leaderboard 
```{r}
# Table of overall player rankings
kable(select(tmp,-Colour,-Team,-`Reverse Points`,Points=`DW Points`))
```

# Overall Standings 

Column 
--------------
### Average Time 
```{r}
final <- final_df(results)
tmp <- filter(final, !is.na(Time))

# plot performance
ggplot(filter(tmp, !is.na(Time)), aes(Time,Player,fill=Player)) +
  geom_col(position='dodge', show.legend=FALSE, colour='black') +
  scale_fill_manual(values = rev(tmp$Colour)) +
  coord_cartesian(xlim=c(min(tmp$Time)*.999,max(tmp$Time)**1.002)) +
  theme_blank() + 
  annotate('text', x=rev(tmp$Time)+.07, #for spacing
           y=1:length(tmp$Time), size=2.5,
           label=paste0(format(rev(tmp$Time),nsmall=2),'s'))
```

Column {data-width=300}
--------------
### Final Scores 
```{r}
# Table of overall player rankings
kable(final %>%
        select(Player,Points=dw_pts) %>%
        arrange(desc(Points)) %>%
        mutate(Rank = 1:nrow(final),.before=1)
)
```






